# @package _global_

defaults:
  - override /agent: dist_matching_embedding_augmented
  - override /configs/env: multiplerooms5_4x4_0
  - override /configs/obs: pixels

num_train_frames: 50000
num_seed_frames: 2000
save_video: false
use_wandb: false

agent:
  data_type: all
  update_actor_every_steps: 1500
  window_size: 10
  unique_window: false
  n_subsamples: 5000
  epsilon_schedule: 0.15
  sink_schedule: linear(0.0,0.004,50000)
  T_init_steps: 50
  feature_dim: 200
  lr_actor: 10
  pmd_steps: 250
  lambda_reg: 1e-6
